# Generated by Django 5.1.3 on 2024-11-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookUser',
        ),
    ]
